"""add_achievement_tables

Revision ID: 0ec3986b88a9
Revises: 9b72d62feac6
Create Date: 2025-12-20 00:34:50.062846

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ec3986b88a9'
down_revision: Union[str, None] = '9b72d62feac6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('achievements',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.String(length=50), nullable=False),
    sa.Column('site_id', sa.String(length=50), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False, comment='唯一标识码'),
    sa.Column('name', sa.String(length=200), nullable=False, comment='显示名称'),
    sa.Column('description', sa.Text(), nullable=True, comment='描述'),
    sa.Column('icon_url', sa.String(length=500), nullable=True, comment='图标 URL'),
    sa.Column('category', sa.String(length=50), nullable=False, comment='分类'),
    sa.Column('tier', sa.Integer(), nullable=False, comment='等级: 1=铜, 2=银, 3=金, 4=钻石'),
    sa.Column('points', sa.Integer(), nullable=False, comment='积分值'),
    sa.Column('rule_type', sa.String(length=50), nullable=False, comment='规则类型: count/event/composite'),
    sa.Column('rule_config', sa.JSON(), nullable=False, comment='规则配置 JSON'),
    sa.Column('is_hidden', sa.Boolean(), nullable=False, comment='是否隐藏成就（解锁前不可见）'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='是否启用'),
    sa.Column('sort_order', sa.Integer(), nullable=False, comment='排序'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_achievements_active', 'achievements', ['is_active'], unique=False)
    op.create_index('ix_achievements_category', 'achievements', ['category'], unique=False)
    op.create_index('ix_achievements_code', 'achievements', ['tenant_id', 'site_id', 'code'], unique=True)
    op.create_index(op.f('ix_achievements_site_id'), 'achievements', ['site_id'], unique=False)
    op.create_index(op.f('ix_achievements_tenant_id'), 'achievements', ['tenant_id'], unique=False)
    op.create_index('ix_achievements_tenant_site', 'achievements', ['tenant_id', 'site_id'], unique=False)
    op.create_table('user_achievements',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.String(length=50), nullable=False),
    sa.Column('site_id', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('achievement_id', sa.Uuid(), nullable=False),
    sa.Column('unlocked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='解锁时间'),
    sa.Column('progress', sa.Integer(), nullable=False, comment='当前进度'),
    sa.Column('progress_target', sa.Integer(), nullable=False, comment='目标值'),
    sa.Column('source', sa.String(length=50), nullable=False, comment='来源: auto/manual'),
    sa.Column('source_ref', sa.String(length=200), nullable=True, comment='来源引用（如触发的事件 ID）'),
    sa.Column('achievement_metadata', sa.JSON(), nullable=True, comment='扩展元数据'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['achievement_id'], ['achievements.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_achievements_achievement_id'), 'user_achievements', ['achievement_id'], unique=False)
    op.create_index(op.f('ix_user_achievements_site_id'), 'user_achievements', ['site_id'], unique=False)
    op.create_index(op.f('ix_user_achievements_tenant_id'), 'user_achievements', ['tenant_id'], unique=False)
    op.create_index('ix_user_achievements_tenant_site', 'user_achievements', ['tenant_id', 'site_id'], unique=False)
    op.create_index('ix_user_achievements_unique', 'user_achievements', ['user_id', 'achievement_id'], unique=True)
    op.create_index('ix_user_achievements_unlocked', 'user_achievements', ['unlocked_at'], unique=False)
    op.create_index('ix_user_achievements_user', 'user_achievements', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_achievements_user_id'), 'user_achievements', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_achievements_user_id'), table_name='user_achievements')
    op.drop_index('ix_user_achievements_user', table_name='user_achievements')
    op.drop_index('ix_user_achievements_unlocked', table_name='user_achievements')
    op.drop_index('ix_user_achievements_unique', table_name='user_achievements')
    op.drop_index('ix_user_achievements_tenant_site', table_name='user_achievements')
    op.drop_index(op.f('ix_user_achievements_tenant_id'), table_name='user_achievements')
    op.drop_index(op.f('ix_user_achievements_site_id'), table_name='user_achievements')
    op.drop_index(op.f('ix_user_achievements_achievement_id'), table_name='user_achievements')
    op.drop_table('user_achievements')
    op.drop_index('ix_achievements_tenant_site', table_name='achievements')
    op.drop_index(op.f('ix_achievements_tenant_id'), table_name='achievements')
    op.drop_index(op.f('ix_achievements_site_id'), table_name='achievements')
    op.drop_index('ix_achievements_code', table_name='achievements')
    op.drop_index('ix_achievements_category', table_name='achievements')
    op.drop_index('ix_achievements_active', table_name='achievements')
    op.drop_table('achievements')
    # ### end Alembic commands ###
