"""add_visitor_profile_tables

Revision ID: 9b72d62feac6
Revises: 71cb7030dab0
Create Date: 2025-12-20 00:01:04.055442

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9b72d62feac6'
down_revision: Union[str, None] = '71cb7030dab0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('visitor_profiles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.String(length=50), nullable=False),
    sa.Column('site_id', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('visit_count', sa.Integer(), nullable=False, comment='访问次数'),
    sa.Column('total_duration_minutes', sa.Integer(), nullable=False, comment='总停留时长（分钟）'),
    sa.Column('conversation_count', sa.Integer(), nullable=False, comment='对话次数'),
    sa.Column('quest_completed_count', sa.Integer(), nullable=False, comment='完成任务数'),
    sa.Column('achievement_count', sa.Integer(), nullable=False, comment='获得成就数'),
    sa.Column('check_in_count', sa.Integer(), nullable=False, comment='打卡次数'),
    sa.Column('favorite_npc_id', sa.Uuid(), nullable=True, comment='最喜欢的 NPC'),
    sa.Column('favorite_scene_id', sa.Uuid(), nullable=True, comment='最喜欢的场景'),
    sa.Column('interest_tags', sa.JSON(), nullable=True, comment='兴趣标签（自动分析）'),
    sa.Column('activity_level', sa.String(length=20), nullable=False, comment='活跃度: new/casual/active/power'),
    sa.Column('engagement_score', sa.Float(), nullable=False, comment='参与度评分 (0-100)'),
    sa.Column('learning_style', sa.String(length=50), nullable=True, comment='学习风格: explorer/achiever/socializer'),
    sa.Column('first_visit_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='首次访问时间'),
    sa.Column('last_visit_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='最后访问时间'),
    sa.Column('last_active_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='最后活跃时间'),
    sa.Column('profile_data', sa.JSON(), nullable=True, comment='扩展画像数据'),
    sa.Column('notes', sa.Text(), nullable=True, comment='备注'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_visitor_profiles_activity', 'visitor_profiles', ['activity_level', 'engagement_score'], unique=False)
    op.create_index(op.f('ix_visitor_profiles_site_id'), 'visitor_profiles', ['site_id'], unique=False)
    op.create_index(op.f('ix_visitor_profiles_tenant_id'), 'visitor_profiles', ['tenant_id'], unique=False)
    op.create_index('ix_visitor_profiles_tenant_site', 'visitor_profiles', ['tenant_id', 'site_id'], unique=False)
    op.create_index(op.f('ix_visitor_profiles_user_id'), 'visitor_profiles', ['user_id'], unique=True)
    op.create_table('visitor_check_ins',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.String(length=50), nullable=False),
    sa.Column('site_id', sa.String(length=50), nullable=False),
    sa.Column('profile_id', sa.Uuid(), nullable=False),
    sa.Column('scene_id', sa.Uuid(), nullable=False, comment='场景 ID'),
    sa.Column('check_in_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='打卡时间'),
    sa.Column('duration_minutes', sa.Integer(), nullable=True, comment='停留时长（分钟）'),
    sa.Column('latitude', sa.Float(), nullable=True, comment='纬度'),
    sa.Column('longitude', sa.Float(), nullable=True, comment='经度'),
    sa.Column('accuracy', sa.Float(), nullable=True, comment='定位精度（米）'),
    sa.Column('photo_count', sa.Integer(), nullable=False, comment='拍照数量'),
    sa.Column('interaction_count', sa.Integer(), nullable=False, comment='交互次数'),
    sa.Column('check_in_metadata', sa.JSON(), nullable=True, comment='扩展元数据'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['visitor_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_visitor_check_ins_profile_id'), 'visitor_check_ins', ['profile_id'], unique=False)
    op.create_index(op.f('ix_visitor_check_ins_scene_id'), 'visitor_check_ins', ['scene_id'], unique=False)
    op.create_index(op.f('ix_visitor_check_ins_site_id'), 'visitor_check_ins', ['site_id'], unique=False)
    op.create_index(op.f('ix_visitor_check_ins_tenant_id'), 'visitor_check_ins', ['tenant_id'], unique=False)
    op.create_index('ix_visitor_check_ins_tenant_site', 'visitor_check_ins', ['tenant_id', 'site_id'], unique=False)
    op.create_index('ix_visitor_check_ins_time', 'visitor_check_ins', ['check_in_at'], unique=False)
    op.create_table('visitor_interactions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.String(length=50), nullable=False),
    sa.Column('site_id', sa.String(length=50), nullable=False),
    sa.Column('profile_id', sa.Uuid(), nullable=False),
    sa.Column('npc_id', sa.Uuid(), nullable=False, comment='NPC ID'),
    sa.Column('conversation_count', sa.Integer(), nullable=False, comment='对话次数'),
    sa.Column('message_count', sa.Integer(), nullable=False, comment='消息数量'),
    sa.Column('total_duration_minutes', sa.Integer(), nullable=False, comment='总对话时长（分钟）'),
    sa.Column('sentiment_score', sa.Float(), nullable=True, comment='情感评分 (-1 到 1)'),
    sa.Column('satisfaction_score', sa.Float(), nullable=True, comment='满意度评分 (0-5)'),
    sa.Column('first_interaction_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='首次交互时间'),
    sa.Column('last_interaction_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='最后交互时间'),
    sa.Column('interaction_data', sa.JSON(), nullable=True, comment='交互详细数据'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['visitor_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_visitor_interactions_npc_id'), 'visitor_interactions', ['npc_id'], unique=False)
    op.create_index(op.f('ix_visitor_interactions_profile_id'), 'visitor_interactions', ['profile_id'], unique=False)
    op.create_index(op.f('ix_visitor_interactions_site_id'), 'visitor_interactions', ['site_id'], unique=False)
    op.create_index(op.f('ix_visitor_interactions_tenant_id'), 'visitor_interactions', ['tenant_id'], unique=False)
    op.create_index('ix_visitor_interactions_tenant_site', 'visitor_interactions', ['tenant_id', 'site_id'], unique=False)
    op.create_index('ix_visitor_interactions_time', 'visitor_interactions', ['last_interaction_at'], unique=False)
    op.create_table('visitor_tags',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.String(length=50), nullable=False),
    sa.Column('site_id', sa.String(length=50), nullable=False),
    sa.Column('profile_id', sa.Uuid(), nullable=False),
    sa.Column('tag_type', sa.String(length=50), nullable=False, comment='标签类型: interest/behavior/achievement/custom'),
    sa.Column('tag_key', sa.String(length=100), nullable=False, comment='标签键'),
    sa.Column('tag_value', sa.String(length=200), nullable=False, comment='标签值'),
    sa.Column('confidence', sa.Float(), nullable=False, comment='置信度 (0-1)'),
    sa.Column('source', sa.String(length=50), nullable=False, comment='来源: auto/manual/ai'),
    sa.Column('source_ref', sa.String(length=200), nullable=True, comment='来源引用（如对话ID、任务ID）'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='是否激活'),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True, comment='过期时间'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['visitor_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_visitor_tags_profile_id'), 'visitor_tags', ['profile_id'], unique=False)
    op.create_index(op.f('ix_visitor_tags_site_id'), 'visitor_tags', ['site_id'], unique=False)
    op.create_index(op.f('ix_visitor_tags_tenant_id'), 'visitor_tags', ['tenant_id'], unique=False)
    op.create_index('ix_visitor_tags_tenant_site', 'visitor_tags', ['tenant_id', 'site_id'], unique=False)
    op.create_index('ix_visitor_tags_type_key', 'visitor_tags', ['tag_type', 'tag_key'], unique=False)
    op.drop_index(op.f('ix_releases_created_at'), table_name='releases')
    op.drop_index(op.f('ix_releases_site_id'), table_name='releases')
    op.drop_index(op.f('ix_releases_status'), table_name='releases')
    op.drop_index(op.f('ix_releases_tenant_id'), table_name='releases')
    op.drop_index(op.f('ix_releases_tenant_site_status'), table_name='releases')
    op.drop_table('releases')
    op.drop_index(op.f('ix_release_history_created_at'), table_name='release_history')
    op.drop_index(op.f('ix_release_history_release_id'), table_name='release_history')
    op.drop_index(op.f('ix_release_history_site_id'), table_name='release_history')
    op.drop_index(op.f('ix_release_history_tenant_id'), table_name='release_history')
    op.drop_table('release_history')
    op.drop_index(op.f('ix_experiment_assignments_experiment_id'), table_name='experiment_assignments')
    op.drop_index(op.f('ix_experiment_assignments_site_id'), table_name='experiment_assignments')
    op.drop_index(op.f('ix_experiment_assignments_subject_key'), table_name='experiment_assignments')
    op.drop_index(op.f('ix_experiment_assignments_tenant_id'), table_name='experiment_assignments')
    op.drop_index(op.f('ix_experiment_assignments_unique'), table_name='experiment_assignments')
    op.drop_index(op.f('ix_experiment_assignments_variant'), table_name='experiment_assignments')
    op.drop_table('experiment_assignments')
    op.drop_index(op.f('ix_experiments_site_id'), table_name='experiments')
    op.drop_index(op.f('ix_experiments_status'), table_name='experiments')
    op.drop_index(op.f('ix_experiments_tenant_id'), table_name='experiments')
    op.drop_index(op.f('ix_experiments_tenant_site_status'), table_name='experiments')
    op.drop_table('experiments')
    op.drop_index(op.f('ix_admin_audit_log_action'), table_name='admin_audit_log')
    op.drop_index(op.f('ix_admin_audit_log_actor'), table_name='admin_audit_log')
    op.drop_index(op.f('ix_admin_audit_log_created_at'), table_name='admin_audit_log')
    op.drop_index(op.f('ix_admin_audit_log_tenant_id'), table_name='admin_audit_log')
    op.drop_table('admin_audit_log')
    op.drop_index(op.f('ix_policies_is_active'), table_name='policies')
    op.drop_index(op.f('ix_policies_policy_type'), table_name='policies')
    op.drop_index(op.f('ix_policies_tenant_id'), table_name='policies')
    op.drop_table('policies')
    op.drop_index(op.f('ix_analytics_events_created_at'), table_name='analytics_events')
    op.drop_index(op.f('ix_contents_body_trgm'), table_name='contents', postgresql_ops={'body': 'gin_trgm_ops'}, postgresql_using='gin')
    op.drop_index(op.f('ix_contents_search_vector'), table_name='contents', postgresql_using='gin')
    op.drop_index(op.f('ix_contents_title_trgm'), table_name='contents', postgresql_ops={'title': 'gin_trgm_ops'}, postgresql_using='gin')
    op.drop_constraint(op.f('conversations_session_id_key'), 'conversations', type_='unique')
    op.drop_index(op.f('ix_conversations_session_id'), table_name='conversations')
    op.create_index(op.f('ix_conversations_session_id'), 'conversations', ['session_id'], unique=True)
    op.alter_column('embedding_usage', 'site_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.drop_index(op.f('ix_embedding_usage_provider_model'), table_name='embedding_usage')
    op.drop_index(op.f('ix_embedding_usage_tenant_created'), table_name='embedding_usage')
    op.drop_index(op.f('ix_evidences_excerpt_trgm'), table_name='evidences', postgresql_ops={'excerpt': 'gin_trgm_ops'}, postgresql_using='gin')
    op.drop_index(op.f('ix_evidences_title_trgm'), table_name='evidences', postgresql_ops={'title': 'gin_trgm_ops'}, postgresql_using='gin')
    op.create_index(op.f('ix_messages_site_id'), 'messages', ['site_id'], unique=False)
    op.create_index(op.f('ix_messages_tenant_id'), 'messages', ['tenant_id'], unique=False)
    op.drop_constraint(op.f('uq_npc_profiles_npc_id_version'), 'npc_profiles', type_='unique')
    op.alter_column('npc_prompts', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.drop_index(op.f('ix_npc_prompt_single_active'), table_name='npc_prompts', postgresql_where='((active = true) AND (deleted_at IS NULL))')
    op.create_index('ix_npc_prompt_active', 'npc_prompts', ['tenant_id', 'site_id', 'npc_id'], unique=False, postgresql_where='active = true AND deleted_at IS NULL')
    op.create_index(op.f('ix_quest_steps_site_id'), 'quest_steps', ['site_id'], unique=False)
    op.create_index(op.f('ix_quest_steps_tenant_id'), 'quest_steps', ['tenant_id'], unique=False)
    op.alter_column('sites', 'timezone',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'Asia/Shanghai'::character varying"))
    op.drop_index(op.f('ix_sites_status'), table_name='sites')
    op.drop_index(op.f('ix_tenants_status'), table_name='tenants')
    op.drop_index(op.f('ix_trace_ledger_created_at'), table_name='trace_ledger')
    op.drop_index(op.f('ix_trace_ledger_experiment_variant_combo'), table_name='trace_ledger')
    op.drop_constraint(op.f('trace_ledger_trace_id_key'), 'trace_ledger', type_='unique')
    op.drop_index(op.f('ix_trace_ledger_trace_id'), table_name='trace_ledger')
    op.create_index(op.f('ix_trace_ledger_trace_id'), 'trace_ledger', ['trace_id'], unique=True)
    op.create_index(op.f('ix_trace_ledger_conversation_id'), 'trace_ledger', ['conversation_id'], unique=False)
    op.alter_column('user_feedbacks', 'resolved_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.drop_index(op.f('ix_user_feedbacks_overdue_scan'), table_name='user_feedbacks')
    op.create_index(op.f('ix_user_feedbacks_conversation_id'), 'user_feedbacks', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_user_feedbacks_message_id'), 'user_feedbacks', ['message_id'], unique=False)
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.drop_constraint(op.f('users_phone_key'), 'users', type_='unique')
    op.drop_constraint(op.f('users_username_key'), 'users', type_='unique')
    op.drop_constraint(op.f('users_wx_openid_key'), 'users', type_='unique')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.drop_index(op.f('ix_users_wx_openid'), table_name='users')
    op.create_index(op.f('ix_users_wx_openid'), 'users', ['wx_openid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_wx_openid'), table_name='users')
    op.create_index(op.f('ix_users_wx_openid'), 'users', ['wx_openid'], unique=False)
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=False)
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=False)
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_unique_constraint(op.f('users_wx_openid_key'), 'users', ['wx_openid'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('users_username_key'), 'users', ['username'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('users_phone_key'), 'users', ['phone'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.drop_index(op.f('ix_user_feedbacks_message_id'), table_name='user_feedbacks')
    op.drop_index(op.f('ix_user_feedbacks_conversation_id'), table_name='user_feedbacks')
    op.create_index(op.f('ix_user_feedbacks_overdue_scan'), 'user_feedbacks', ['status', 'sla_due_at', 'overdue_flag'], unique=False)
    op.alter_column('user_feedbacks', 'resolved_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.drop_index(op.f('ix_trace_ledger_conversation_id'), table_name='trace_ledger')
    op.drop_index(op.f('ix_trace_ledger_trace_id'), table_name='trace_ledger')
    op.create_index(op.f('ix_trace_ledger_trace_id'), 'trace_ledger', ['trace_id'], unique=False)
    op.create_unique_constraint(op.f('trace_ledger_trace_id_key'), 'trace_ledger', ['trace_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_trace_ledger_experiment_variant_combo'), 'trace_ledger', ['experiment_id', 'experiment_variant'], unique=False)
    op.create_index(op.f('ix_trace_ledger_created_at'), 'trace_ledger', ['created_at'], unique=False)
    op.create_index(op.f('ix_tenants_status'), 'tenants', ['status'], unique=False)
    op.create_index(op.f('ix_sites_status'), 'sites', ['status'], unique=False)
    op.alter_column('sites', 'timezone',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'Asia/Shanghai'::character varying"))
    op.drop_index(op.f('ix_quest_steps_tenant_id'), table_name='quest_steps')
    op.drop_index(op.f('ix_quest_steps_site_id'), table_name='quest_steps')
    op.drop_index('ix_npc_prompt_active', table_name='npc_prompts', postgresql_where='active = true AND deleted_at IS NULL')
    op.create_index(op.f('ix_npc_prompt_single_active'), 'npc_prompts', ['tenant_id', 'site_id', 'npc_id'], unique=True, postgresql_where='((active = true) AND (deleted_at IS NULL))')
    op.alter_column('npc_prompts', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.create_unique_constraint(op.f('uq_npc_profiles_npc_id_version'), 'npc_profiles', ['npc_id', 'version'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_messages_tenant_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_site_id'), table_name='messages')
    op.create_index(op.f('ix_evidences_title_trgm'), 'evidences', ['title'], unique=False, postgresql_ops={'title': 'gin_trgm_ops'}, postgresql_using='gin')
    op.create_index(op.f('ix_evidences_excerpt_trgm'), 'evidences', ['excerpt'], unique=False, postgresql_ops={'excerpt': 'gin_trgm_ops'}, postgresql_using='gin')
    op.create_index(op.f('ix_embedding_usage_tenant_created'), 'embedding_usage', ['tenant_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_embedding_usage_provider_model'), 'embedding_usage', ['provider', 'model'], unique=False)
    op.alter_column('embedding_usage', 'site_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.drop_index(op.f('ix_conversations_session_id'), table_name='conversations')
    op.create_index(op.f('ix_conversations_session_id'), 'conversations', ['session_id'], unique=False)
    op.create_unique_constraint(op.f('conversations_session_id_key'), 'conversations', ['session_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_contents_title_trgm'), 'contents', ['title'], unique=False, postgresql_ops={'title': 'gin_trgm_ops'}, postgresql_using='gin')
    op.create_index(op.f('ix_contents_search_vector'), 'contents', ['search_vector'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_contents_body_trgm'), 'contents', ['body'], unique=False, postgresql_ops={'body': 'gin_trgm_ops'}, postgresql_using='gin')
    op.create_index(op.f('ix_analytics_events_created_at'), 'analytics_events', ['created_at'], unique=False)
    op.create_table('policies',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('policy_type', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('version', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('activated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('policies_pkey')),
    sa.UniqueConstraint('tenant_id', 'policy_type', 'version', name=op.f('policies_tenant_id_policy_type_version_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_policies_tenant_id'), 'policies', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_policies_policy_type'), 'policies', ['policy_type'], unique=False)
    op.create_index(op.f('ix_policies_is_active'), 'policies', ['is_active'], unique=False)
    op.create_table('admin_audit_log',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('actor', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('action', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('target_type', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('target_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('admin_audit_log_pkey'))
    )
    op.create_index(op.f('ix_admin_audit_log_tenant_id'), 'admin_audit_log', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_admin_audit_log_created_at'), 'admin_audit_log', ['created_at'], unique=False)
    op.create_index(op.f('ix_admin_audit_log_actor'), 'admin_audit_log', ['actor'], unique=False)
    op.create_index(op.f('ix_admin_audit_log_action'), 'admin_audit_log', ['action'], unique=False)
    op.create_table('experiments',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('site_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'draft'::character varying"), autoincrement=False, nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False),
    sa.Column('start_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('end_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='experiments_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_experiments_tenant_site_status'), 'experiments', ['tenant_id', 'site_id', 'status'], unique=False)
    op.create_index(op.f('ix_experiments_tenant_id'), 'experiments', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_experiments_status'), 'experiments', ['status'], unique=False)
    op.create_index(op.f('ix_experiments_site_id'), 'experiments', ['site_id'], unique=False)
    op.create_table('experiment_assignments',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('experiment_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('site_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('subject_type', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('subject_key', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('variant', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('bucket_hash', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('strategy_overrides', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False),
    sa.Column('assigned_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.id'], name=op.f('experiment_assignments_experiment_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('experiment_assignments_pkey'))
    )
    op.create_index(op.f('ix_experiment_assignments_variant'), 'experiment_assignments', ['variant'], unique=False)
    op.create_index(op.f('ix_experiment_assignments_unique'), 'experiment_assignments', ['experiment_id', 'subject_key'], unique=True)
    op.create_index(op.f('ix_experiment_assignments_tenant_id'), 'experiment_assignments', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_experiment_assignments_subject_key'), 'experiment_assignments', ['subject_key'], unique=False)
    op.create_index(op.f('ix_experiment_assignments_site_id'), 'experiment_assignments', ['site_id'], unique=False)
    op.create_index(op.f('ix_experiment_assignments_experiment_id'), 'experiment_assignments', ['experiment_id'], unique=False)
    op.create_table('release_history',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('release_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('site_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('action', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('previous_release_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('operator', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('release_history_pkey'))
    )
    op.create_index(op.f('ix_release_history_tenant_id'), 'release_history', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_release_history_site_id'), 'release_history', ['site_id'], unique=False)
    op.create_index(op.f('ix_release_history_release_id'), 'release_history', ['release_id'], unique=False)
    op.create_index(op.f('ix_release_history_created_at'), 'release_history', ['created_at'], unique=False)
    op.create_table('releases',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('site_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('activated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('archived_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('releases_pkey'))
    )
    op.create_index(op.f('ix_releases_tenant_site_status'), 'releases', ['tenant_id', 'site_id', 'status'], unique=False)
    op.create_index(op.f('ix_releases_tenant_id'), 'releases', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_releases_status'), 'releases', ['status'], unique=False)
    op.create_index(op.f('ix_releases_site_id'), 'releases', ['site_id'], unique=False)
    op.create_index(op.f('ix_releases_created_at'), 'releases', ['created_at'], unique=False)
    op.drop_index('ix_visitor_tags_type_key', table_name='visitor_tags')
    op.drop_index('ix_visitor_tags_tenant_site', table_name='visitor_tags')
    op.drop_index(op.f('ix_visitor_tags_tenant_id'), table_name='visitor_tags')
    op.drop_index(op.f('ix_visitor_tags_site_id'), table_name='visitor_tags')
    op.drop_index(op.f('ix_visitor_tags_profile_id'), table_name='visitor_tags')
    op.drop_table('visitor_tags')
    op.drop_index('ix_visitor_interactions_time', table_name='visitor_interactions')
    op.drop_index('ix_visitor_interactions_tenant_site', table_name='visitor_interactions')
    op.drop_index(op.f('ix_visitor_interactions_tenant_id'), table_name='visitor_interactions')
    op.drop_index(op.f('ix_visitor_interactions_site_id'), table_name='visitor_interactions')
    op.drop_index(op.f('ix_visitor_interactions_profile_id'), table_name='visitor_interactions')
    op.drop_index(op.f('ix_visitor_interactions_npc_id'), table_name='visitor_interactions')
    op.drop_table('visitor_interactions')
    op.drop_index('ix_visitor_check_ins_time', table_name='visitor_check_ins')
    op.drop_index('ix_visitor_check_ins_tenant_site', table_name='visitor_check_ins')
    op.drop_index(op.f('ix_visitor_check_ins_tenant_id'), table_name='visitor_check_ins')
    op.drop_index(op.f('ix_visitor_check_ins_site_id'), table_name='visitor_check_ins')
    op.drop_index(op.f('ix_visitor_check_ins_scene_id'), table_name='visitor_check_ins')
    op.drop_index(op.f('ix_visitor_check_ins_profile_id'), table_name='visitor_check_ins')
    op.drop_table('visitor_check_ins')
    op.drop_index(op.f('ix_visitor_profiles_user_id'), table_name='visitor_profiles')
    op.drop_index('ix_visitor_profiles_tenant_site', table_name='visitor_profiles')
    op.drop_index(op.f('ix_visitor_profiles_tenant_id'), table_name='visitor_profiles')
    op.drop_index(op.f('ix_visitor_profiles_site_id'), table_name='visitor_profiles')
    op.drop_index('ix_visitor_profiles_activity', table_name='visitor_profiles')
    op.drop_table('visitor_profiles')
    # ### end Alembic commands ###
