"""add_solar_term_and_iot_tables

Revision ID: ae727f3d9b63
Revises: 0ec3986b88a9
Create Date: 2025-12-20 01:00:35.117712

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae727f3d9b63'
down_revision: Union[str, None] = '0ec3986b88a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('farming_knowledge',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.String(length=50), nullable=False),
    sa.Column('site_id', sa.String(length=50), nullable=False),
    sa.Column('solar_term_code', sa.String(length=50), nullable=True, comment='关联节气代码'),
    sa.Column('category', sa.String(length=50), nullable=False, comment='分类: crop/tool/technique/custom/general'),
    sa.Column('title', sa.String(length=200), nullable=False, comment='标题'),
    sa.Column('content', sa.Text(), nullable=False, comment='内容'),
    sa.Column('media_urls', sa.JSON(), nullable=True, comment='图片/视频 URL'),
    sa.Column('related_pois', sa.JSON(), nullable=True, comment='关联兴趣点'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='是否启用'),
    sa.Column('sort_order', sa.Integer(), nullable=False, comment='排序'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_farming_knowledge_category', 'farming_knowledge', ['category'], unique=False)
    op.create_index(op.f('ix_farming_knowledge_site_id'), 'farming_knowledge', ['site_id'], unique=False)
    op.create_index(op.f('ix_farming_knowledge_solar_term_code'), 'farming_knowledge', ['solar_term_code'], unique=False)
    op.create_index(op.f('ix_farming_knowledge_tenant_id'), 'farming_knowledge', ['tenant_id'], unique=False)
    op.create_index('ix_farming_knowledge_tenant_site', 'farming_knowledge', ['tenant_id', 'site_id'], unique=False)
    op.create_index('ix_farming_knowledge_term', 'farming_knowledge', ['solar_term_code'], unique=False)
    op.create_table('iot_devices',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.String(length=50), nullable=False),
    sa.Column('site_id', sa.String(length=50), nullable=False),
    sa.Column('device_code', sa.String(length=100), nullable=False, comment='设备编码'),
    sa.Column('name', sa.String(length=200), nullable=False, comment='设备名称'),
    sa.Column('device_type', sa.String(length=50), nullable=False, comment='设备类型'),
    sa.Column('location', sa.String(length=500), nullable=True, comment='位置描述'),
    sa.Column('scene_id', sa.Uuid(), nullable=True, comment='关联场景'),
    sa.Column('poi_id', sa.Uuid(), nullable=True, comment='关联兴趣点'),
    sa.Column('config', sa.JSON(), nullable=True, comment='设备配置'),
    sa.Column('status', sa.String(length=50), nullable=False, comment='设备状态'),
    sa.Column('last_heartbeat', sa.DateTime(timezone=True), nullable=True, comment='最后心跳时间'),
    sa.Column('device_metadata', sa.JSON(), nullable=True, comment='扩展元数据'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='是否启用'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_iot_devices_code', 'iot_devices', ['tenant_id', 'site_id', 'device_code'], unique=True)
    op.create_index(op.f('ix_iot_devices_poi_id'), 'iot_devices', ['poi_id'], unique=False)
    op.create_index(op.f('ix_iot_devices_scene_id'), 'iot_devices', ['scene_id'], unique=False)
    op.create_index(op.f('ix_iot_devices_site_id'), 'iot_devices', ['site_id'], unique=False)
    op.create_index('ix_iot_devices_status', 'iot_devices', ['status'], unique=False)
    op.create_index(op.f('ix_iot_devices_tenant_id'), 'iot_devices', ['tenant_id'], unique=False)
    op.create_index('ix_iot_devices_tenant_site', 'iot_devices', ['tenant_id', 'site_id'], unique=False)
    op.create_index('ix_iot_devices_type', 'iot_devices', ['device_type'], unique=False)
    op.create_table('solar_terms',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False, comment='唯一标识码'),
    sa.Column('name', sa.String(length=50), nullable=False, comment='节气名称'),
    sa.Column('order', sa.Integer(), nullable=False, comment='顺序 1-24'),
    sa.Column('month', sa.Integer(), nullable=False, comment='公历月份'),
    sa.Column('day_start', sa.Integer(), nullable=False, comment='起始日（约数）'),
    sa.Column('day_end', sa.Integer(), nullable=False, comment='结束日（约数）'),
    sa.Column('description', sa.Text(), nullable=True, comment='节气描述'),
    sa.Column('farming_advice', sa.Text(), nullable=True, comment='农耕建议'),
    sa.Column('cultural_customs', sa.JSON(), nullable=True, comment='文化习俗'),
    sa.Column('poems', sa.JSON(), nullable=True, comment='相关诗词'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index('ix_solar_terms_month', 'solar_terms', ['month'], unique=False)
    op.create_index('ix_solar_terms_order', 'solar_terms', ['order'], unique=False)
    op.create_table('iot_device_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.String(length=50), nullable=False),
    sa.Column('site_id', sa.String(length=50), nullable=False),
    sa.Column('device_id', sa.Uuid(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False, comment='事件类型'),
    sa.Column('event_data', sa.JSON(), nullable=True, comment='事件数据'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['iot_devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_iot_device_logs_created', 'iot_device_logs', ['created_at'], unique=False)
    op.create_index('ix_iot_device_logs_device', 'iot_device_logs', ['device_id'], unique=False)
    op.create_index(op.f('ix_iot_device_logs_device_id'), 'iot_device_logs', ['device_id'], unique=False)
    op.create_index(op.f('ix_iot_device_logs_site_id'), 'iot_device_logs', ['site_id'], unique=False)
    op.create_index(op.f('ix_iot_device_logs_tenant_id'), 'iot_device_logs', ['tenant_id'], unique=False)
    op.create_index('ix_iot_device_logs_tenant_site', 'iot_device_logs', ['tenant_id', 'site_id'], unique=False)
    op.create_index('ix_iot_device_logs_type', 'iot_device_logs', ['event_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_iot_device_logs_type', table_name='iot_device_logs')
    op.drop_index('ix_iot_device_logs_tenant_site', table_name='iot_device_logs')
    op.drop_index(op.f('ix_iot_device_logs_tenant_id'), table_name='iot_device_logs')
    op.drop_index(op.f('ix_iot_device_logs_site_id'), table_name='iot_device_logs')
    op.drop_index(op.f('ix_iot_device_logs_device_id'), table_name='iot_device_logs')
    op.drop_index('ix_iot_device_logs_device', table_name='iot_device_logs')
    op.drop_index('ix_iot_device_logs_created', table_name='iot_device_logs')
    op.drop_table('iot_device_logs')
    op.drop_index('ix_solar_terms_order', table_name='solar_terms')
    op.drop_index('ix_solar_terms_month', table_name='solar_terms')
    op.drop_table('solar_terms')
    op.drop_index('ix_iot_devices_type', table_name='iot_devices')
    op.drop_index('ix_iot_devices_tenant_site', table_name='iot_devices')
    op.drop_index(op.f('ix_iot_devices_tenant_id'), table_name='iot_devices')
    op.drop_index('ix_iot_devices_status', table_name='iot_devices')
    op.drop_index(op.f('ix_iot_devices_site_id'), table_name='iot_devices')
    op.drop_index(op.f('ix_iot_devices_scene_id'), table_name='iot_devices')
    op.drop_index(op.f('ix_iot_devices_poi_id'), table_name='iot_devices')
    op.drop_index('ix_iot_devices_code', table_name='iot_devices')
    op.drop_table('iot_devices')
    op.drop_index('ix_farming_knowledge_term', table_name='farming_knowledge')
    op.drop_index('ix_farming_knowledge_tenant_site', table_name='farming_knowledge')
    op.drop_index(op.f('ix_farming_knowledge_tenant_id'), table_name='farming_knowledge')
    op.drop_index(op.f('ix_farming_knowledge_solar_term_code'), table_name='farming_knowledge')
    op.drop_index(op.f('ix_farming_knowledge_site_id'), table_name='farming_knowledge')
    op.drop_index('ix_farming_knowledge_category', table_name='farming_knowledge')
    op.drop_table('farming_knowledge')
    # ### end Alembic commands ###
